name: War/Peace
favicon: null
layout_spectrum: 0.14277239725925028
typography_spectrum: 0.17219888768158853
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.7229707664810121
  lightness: 0.04188199806958437
  saturation: 0.11711656162515283
  rhythmicContrast: 0.5265795502346009
purpose: []
