name: War/Peace
favicon: null
layout_spectrum: 0.24461
typography_spectrum: 0.93848
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#cc0001'
    - '#707070'
    - '#bababa'
  brandStrength: 0.5
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
